version: "3.8"
services: 
  springboot-app:
    image: springboot-app
    build: .
    ports:
      - "8082:8080"
    environment:
      MYSQL_HOST: 18.222.108.56
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      MYSQL_PORT: 3306
